# Generated by Django 5.2.6 on 2025-11-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_description_city_icon_city_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.CharField(blank=True, null=True),
        ),
    ]
