# Generated by Django 5.2.6 on 2025-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city_lat_city_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='feels_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
